use ICP_db;

CREATE TABLE IF NOT EXISTS `doctor_tbl`(
   `d_id` VARCHAR(20) NOT NULL,
   `d_name` VARCHAR(20) NOT NULL,
   `d_tel` VARCHAR(20) NOT NULL,
   `d_pwd` VARCHAR(255) NOT NULL,
   PRIMARY KEY ( `d_id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `patient_tbl`(
   `p_id` INT UNSIGNED AUTO_INCREMENT,
   `p_name` VARCHAR(20) NOT NULL,
   `p_age` INT NOT NULL,
   `p_gender` VARCHAR(5) NOT NULL,
   PRIMARY KEY ( `p_id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `consultation_tbl`(
   `c_id` INT UNSIGNED AUTO_INCREMENT,
   `p_id` INT UNSIGNED NOT NULL,
   `c_date` DATETIME NOT NULL,
   `sympton` VARCHAR(512) NOT NULL,
   `diagnosis` VARCHAR(512) NOT NULL,
   PRIMARY KEY ( `c_id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ICP_tbl`(
   `i_id` INT UNSIGNED AUTO_INCREMENT,
   `p_id` INT UNSIGNED NOT NULL,
   `i_date` DATETIME NOT NULL,
   `i_data` VARCHAR(512) NOT NULL,
   PRIMARY KEY ( `i_id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
